int nvprep (int, int *);
int nv1ini( int, int *);
int nv2ini( int, int *);
int nv3ini( int, int *);
int nv1eas( double, double, double, double *, double *, double *);
int nv2eas( double, double, double, double *, double *, double *);
int nv3eas( double, double, double, double *, double *, double *);
int nv1sae( double, double, double, double *, double *, double *);
int nv2sae( double, double, double, double *, double *, double *);
int nv3sae( double, double, double, double *, double *, double *);
int nv1opt( int, double *, double *);
int nv2opt( int, double *, double *);
int nv3opt( int, double *, double *);
