void araget_(int *fd, int *offset, int *nbyte, int *buf);
int BTEST(int , int );
long bword (long *, int , int );
double flalo (long );
float fsign (float , float );
int modrnd (int ,int );
int dyofyr (int , long , int );
void etoa (char *, int );
long exbits (int , int , unsigned char *);
int fltcon (float *, long );
double w0ftime (int );
