'\"
'\" $Id$
.TH mcInfo 1 "26 June 1990"
.SH NAME
mcInfo \- get information from McIDAS Area File ``Area Directory''
.SH "UNIX SYNOPSIS"
\fBmcInfo \fR[\fB\-v\fR]
[\fIfile ...\fR]
.SH DESCRIPTION
This program is used primarily to construct a meaningful file name for 
an ``Area file'' image file, using descriptive information contained within
the file.
.SH OPTIONS 
.TP 8
.B \-v
Verbose flag.  If present, print ALL the fields in the ``Area Directory''.
.SH "SEE ALSO"
.SH DIAGNOSTICS
