#!/bin/csh
#
# Copyright (c)1993 UCAR/Unidata
#
# Permission to use, copy, modify, and distribute this software and its
# documentation for any purpose without fee is hereby granted, provided
# that the above copyright notice appear in all copies, that both that
# copyright notice and this permission notice appear in supporting
# documentation, and that the name of UCAR/Unidata not be used in
# advertising or publicity pertaining to distribution of the software
# without specific, written prior permission.  UCAR makes no
# representations about the suitability of this software for any purpose.
# It is provided "as is" without express or implied warranty.  It is
# provided with no support and without obligation on the part of UCAR or
# Unidata, to assist in its use, correction, modification, or enhancement.
#
# arealinks: Set up links to the directory containing McIDAS AREA files.
#            The links have the TDDHH file naming convention for the sat 
#            files, where T is type (i=IR, v=VIS, w=Water Vapor, f=Floater
#            and c=Composite (antartic)), DD is the 2 digit day, and HH
#            is the two digit hour. You may reconfigure this script to
#            change the naming convention if you'd like.  The date and 
#            time is determined by opening the AREA file and extracting
#            the valid time information using a program called mcInfo
#            written by Tom Yoksas of the Unidata Program Center.  mcInfo
#            is included with this software package.  If you are currently
#            running mcInfo for WXP or McIDAS, you do not need to rebuild
#            the mcInfo executable.
#            Note, the user needs write permission in the GEMPAK area
#            directory. Run the script from cron after products arrive:
#
# #Create links from area files to wxp convention in ~ldm/data/unidata/mcidas
# 21 * * * * /bin/csh /home/nawips/bin/arealinks vis 1>>/dev/null 2>&1
# 33 * * * * /bin/csh /home/nawips/bin/arealinks ir 1>>/dev/null 2>&1
# 40 * * * * /bin/csh /home/nawips/bin/arealinks float 1>>/dev/null 2>&1
# 55 * * * * /bin/csh /home/nawips/bin/arealinks wv 1>>/dev/null 2>&1
# 59 * * * * /bin/csh /home/nawips/bin/arealinks comp  1>>/dev/null 2>&1
#
# usage:  arealinks [type]
#                   where type = vis   Visible area files (0120-0129)
#                                ir    IR area files (0130-0139)
#                                wv    Water Vapor area files (0170-0179)
#				 float Floater images (0160-0169)
#                                comp  Antartic composite images (0190-0199)
#
# programs used:  mcInfo    - extract header information from area files.
#
# NOTE TO USER:  IN 1995 YOU MUST CHANGE ALL OCCURANCES OF THE NUMBER 94 
# TO 95 IN THIS SCRIPT.  THE SED SUBSTITUTE COMMAND CURRENTLY KEYS ON THE
# NUMBER 94 TO CREATE THE LINK.  SIMPLY CHANGE 94 TO 95, AND THE SCRIPT
# WILL KEEP WORKING!
#
# LOG:
# M.Wright/Unidata		Wrote areatomca
# P.Bruehl/Unidata	10/94	Recast areatomca to arealinks for GEMPAK use
#
###############################################################################
#
# User specified variables:
#
# Directory holding the AREA files:

set areadir=/var/data/ldm/unidata/mcidas

# Directory to hold the links (can be the same as areadir):

set gemdir=/var/data/ldm/gempak/AREA

############################################################################## 

set tmp=/tmp/temp.$$
cd $areadir

if ("$1" == "vis") then
   rm ${gemdir}/v*
   foreach file (`ls -lt [aA][rR][eE][aA]012? | awk '{print$NF}'`)
      /home/nawips/bin/mcInfo $file > $tmp
      set newfile=`cat $tmp | sed 's/94../v/' | sed 's/_.*//'`
      ln -s $areadir/$file ${gemdir}/$newfile
   end
endif

if ("$1" == "ir") then
   rm ${gemdir}/i*
   foreach file (`ls -lt [aA][rR][eE][aA]013? | awk '{print$NF}'`)
      /home/nawips/bin/mcInfo $file > $tmp
      set newfile=`cat $tmp | sed 's/94../i/' | sed 's/_.*//'`
      ln -s $areadir/$file ${gemdir}/$newfile
   end
endif

if ("$1" == "wv") then
   rm ${gemdir}/w*
   foreach file (`ls -lt [aA][rR][eE][aA]017? | awk '{print$NF}'`)
      /home/nawips/bin/mcInfo $file > $tmp
      set newfile=`cat $tmp | sed 's/94../w/' | sed 's/_.*//'`
      ln -s $areadir/$file ${gemdir}/$newfile
   end
endif

if ("$1" == "float") then
   rm ${gemdir}/f*
   foreach file (`ls -lt [aA][rR][eE][aA]016? | awk '{print$NF}'`)
      /home/nawips/bin/mcInfo $file > $tmp
      set newfile=`cat $tmp | sed 's/94../f/' | sed 's/_.*//'`
      ln -s $areadir/$file ${gemdir}/$newfile
   end
endif

#if ("$1" == "moll") then
#   rm ${gemdir}/m*
#   foreach file (`ls -lt [aA][rR][eE][aA]014? | awk '{print$NF}'`)
#      /home/gempak/nawips/binsol/mcInfo $file > $tmp
#      set newfile=`cat $tmp | sed 's/94../m/' | sed 's/_.*//'`
#      ln -s $areadir/$file ${gemdir}/$newfile
#   end
#endif

if ("$1" == "comp") then
   rm ${gemdir}/c*
   foreach file (`ls -lt [aA][rR][eE][aA]019? | awk '{print$NF}'`)
      /home/nawips/bin/mcInfo $file > $tmp
      set newfile=`cat $tmp | sed 's/94../c/' | sed 's/_.*//'`
      ln -s $areadir/$file ${gemdir}/$newfile
   end

endif
rm $tmp
exit
