#!/bin/csh
#
# EZPIVA
#
# This script displays the vorticity advection by the 700-300 mb thermal
# wind along with the 500 mb winds and 850-500 mb lapse rate.
#
# No command line parameters are requried.
#
#	Syntax:  ezpiva
#
##
# Log:
# B. Colman/SEA		 1994
# R. Miller/COMET	 1994
# S. Jacobs/NMC		10/94	Clean up
#

# Source the file called settings.  This file contains commands to set
# environment variables for the model name and device driver.

source settings

gdcntr << EOF
GDATTIM = all
GLEVEL  = 500
GVCORD  = pres
GFUNC   = adv(avor(wnd),thrm@300:700)
CINT    = 8
LINE    = 22/-2/1
TITLE   = 1=white/-3/~  $model  @ UPWARD PIVA (SHADED)
DEVICE  = $dev
CLEAR   = yes
PANEL   = 0
SCALE   = 10
CONTUR  = 1
HILO    =
SKIP    =
FINT    = 8/8
FLINE   = 101;21-30
CTYPE   = f/c
r

CLEAR   = no
GFUNC   = mul(1000.,quo(sub(tmpc@850,tmpc),sub(hght,hght@850)))
CINT    = 1
SCALE   = 0
LINE    = 7/-2/2
TITLE   = 1=white/-2/850-500 MB LAPSE RATE (C/KM; CONTOURS)
CTYPE   = c
r

ex
EOF

gdwind << EOFF
GVECT   = wnd
WIND    = bk20/1.3/2
TITLE   = 1=white/-1/AND 500-MB WINDS
SKIP    = /1
r

;2
;l
ex
EOFF
