SOURCES= odtauto.o odtdata.o odtfft.o odtfuncs.o odthistory.o odtintensity.o \
	odtoutput.o odtscene.o odttopo.o 

CFLAGS= -w -ansi -pedantic -fno-common -g
CC=gcc
AR= ar
ARFLAGS= ruv

.SUFFIXES:	.c

c.o:
	$(CC) $(CFLAGS) -c $<
AODTLIB = libaodtlib.a
all     : src $(AODTLIB)
src     : $(SOURCES)
$(AODTLIB) : $(SOURCES)
	$(AR) $(ARFLAGS) $@ $?
clean :
	rm -f $(SOURCES)

