#!/bin/csh

if ( ${1} == "" )  then
	echo "Must input alphabetically-sorted table filename on cammand line."
	exit
endif

set infile=${1}
set outfile="$GEMTBL/cities/${infile}.info"

echo "Creating information file $outfile from ${infile}"

naminfo.$NA_OS  ${infile}  > $GEMTBL/cities/${infile}.info

exit
