'\"
'\" $Header: /usr/local/ldm/src/ldm4/gribtogem/RCS/gribtogem.1,v 1.2 1992/11/12 00:17:01 davis Exp $
.TH GRIBTOGEM 1 "26 June 1995"
.SH NAME
gribtogem version 2 - GRIB/GEMPAK decoder client for the Unidata LDM
.SH "UNIX SYNOPSIS"
\fBgribtogem [\fB\-l \fIlogfile\fR] \fR[\fB\-v\fR] \fR[\fB\-t timeout\fR] \fR[\fB\-x\fR]
 \fR[\fB\-e errfile\fR] \fR[\fB\-q meth\fR]
\fR[\fIPACK\fR] \fIGEMPAK_file\fR
.SH DESCRIPTION
This program decodes GRIB products on the NWS High Resolution Data Service (HRS)
feed, writing the decoded products into a specified GEMPAK output file.  It
can run as a subprocess of the LDM4 server, receiving a stream of GRIB
products from standard input.
.B gribtogem
can also be used as a stand alone decoder, decoding products on its standard
input into GEMPAK form, as specified by
.I GEMPAK_file.
The file will be stored in the GEMPAK GRIB format if the optional
.I PACK
parameter is present.

.B gribtogem
is part of the Unidata Local Data Management system (LDM).
In case it is to be run as a subprocess of the LDM server,
.B gribtogem
should be used with the PIPE action of the LDM server, from a pattern-action
entry.  The form of such an entry is:

  WMO	\fIpattern\fR	PIPE	\fIgribtogem-executable\fR  gribtogem
				\fIPACK\fR	\fIGEMPAK-file\fR

where \fIpattern\fR is a regular expression pattern matching WMO headers of
products that are to be decoded and written to the output file
\fIGEMPAK-file\fR.
Any directories that do not exist in \fIGEMPAK-file\fR
will be created as needed, so date components, for example, may be part of
the output file path, specified by using matched parts of the regular
expression \fIpattern\fR.

The path of the executable for \fIgribtogem\fR must be specified as the first
argument to the PIPE command, and should be either an absolute path name or
in a directory in the executable search path of the LDM4 server.

The \fIgribtogem\fR program reads its standard input for products passed to
it from the LDM4 server, or it may be invoked independently of the server to
decode GRIB products from its standard input.

.SH OPTIONS 
.TP 8
.BI \-l " logfile"
The path name of a file to be used as the log file for the process.  If "-"
is specified as the logfile or no logfile is specified, the default is
standard error.  If \fIgribtogem\fR processes use the same log file as the
LDM4 server and NPS ingester, any problems are easier to diagnose.
.TP
.B \-v
Verbose flag.  If present, the log will contain messages for each product
that was recieved and successfully decoded, messages explaining why products
that were not decoded were skipped, and on termination a summary of totals
products seen, decoded and written.
.TP 8
.BI \-t " timeout"
Timeout in seconds (default is 600).  If there has been no input available
on stdin for the duration of the specified timeout, the program exits
gracefully.
.TP
.BI \-x
Turn on debugging.  This may produce extra debugging output in the log file.
.TP 
.BI \-e " errfile"
Append bad GRIB products to this file.  Bad GRIB products are products 
that are too short, or too long, or somehow un-decodable.
.TP
.BI \q " meth"
Specification for expanding quasi-regular grids, e.g. -q
"lin,dlat=2.5,dlon=5.0". This is useful for "thickening" the thinned
global Aviation Model grids from NMC. The currently available methods
are lin (linear interpolation) and cub (cubic spline). Currently, each
quasi-regular grid is expanded as it arrives, and before any assembling
of global grids is done. This means for the Aviation model, each of the
8 octants are interpolated individually, and not a as a global grid.
You may specify the output resolution of the grid. One restriction is
that the dlat & dlon must be evenly divisible into the expanded size of
the grid. For the Aviation model, each octant (subgrid) is 90 degrees
latitude by 90 degrees longitude. GEMPAK code has a limitation of LLMXGD
(24,000 for most platforms) grid points. For global grids, this means
that dlat=1.25 by dlon=2.5 is about as fine a resolution that will fit
into a GEMPAK grid file. If you need finer resolution, you will need to
change the value for LLMXGD in the file $GEMPAK/include/GEMPRM.PRM
to a larger number, and completely reinstall GEMPAK. A restriction on
the cubic spline method is that dlat must be a multiple of the input
grid resolution. For example, if the input grid resolution is 1.25x1.25
degrees, you could use dlat=2.5, but not dlat=3.0.
.TP
.BI "PACK"
If present, the data will be stored in the GEMPAK GRIB format.
Otherwise the data will be stored as floating point numbers.
.TP
.BI "GEMPAK_file"
The path name of the GEMPAK output file.
This may be specified as an absolute path name or (more
typically) relative to the directory from which \fIgribtogem\fR is invoked.
Directories that do not exist in the path name of the output file
will be created as needed.

.SH EXAMPLE
The command
.RS +4
.nf

gribtogem PACK 95050512_nX.gem < 95050512_X.wmo

.fi
.RE
will decode the products in 95050512_X.wmo into the GEMPAK file
95050512_nX.gem in GEMPAK GRIB format.

The command
.RS +4
.nf

gribtogem -xvl logfile -e badgribs -q "lin,dlat=1.25,dlon=2.5" PACK 
95050512_thin.gem < 95050512_thin.wmo

.fi
.RE
will expand and decode the quasi-regular GRIB products in 95050512_thin.wmo 
into the GEMPAK file 95050512_thin.gem in GEMPAK GRIB format using the
linear interpolation method.  The
resolution of the grids will be 1.25 deg lat by 2.5 deg lon.

The command
.RS +4
.nf

gribtogem -xvl logfile -e badgribs -q "cub,dlat=2.5,dlon=2.5" PACK 
95050512_thin.gem < 95050512_thin.wmo

.fi
.RE
will expand and decode the quasi-regular GRIB products in 95050512_thin.wmo 
into the GEMPAK file 95050512_cubic.gem in GEMPAK GRIB format using
the cubic spline interpolation method.  The
resolution of the grids will be 2.5 deg lat by 2.5 deg lon.

.SH "SEE ALSO"
cdl(5), gribtonc(1), netcdf(5), ldmd(1)
.SH DIAGNOSTICS
Error messages and log messages are written to the log file.

