
#define PACKAGE_NAME ""
#define PACKAGE_TARNAME ""
#define PACKAGE_VERSION ""
#define PACKAGE_STRING ""
#define PACKAGE_BUGREPORT ""
#define PACKAGE "pkg-config"
#define VERSION "0.20"
#define STDC_HEADERS 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_SYS_STAT_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRING_H 1
#define HAVE_MEMORY_H 1
#define HAVE_STRINGS_H 1
#define HAVE_INTTYPES_H 1
#define HAVE_UNISTD_H 1
#define HAVE_DLFCN_H 1
#define ENABLE_INDIRECT_DEPS 0
#define HAVE_ALLOCA_H 1
#define HAVE_ALLOCA 1
#define HAVE_SETREUID 1
#define HAVE_DIRENT_H 1
#define HAVE_UNISTD_H 1
#define HAVE_SYS_WAIT_H 1
