#!/bin/csh
#
#       Script to produce a suite of plots from the ECMWF model.
#
#       The following products are plotted:
#
#       72, 96, 120, 144hr fcst from 12Z,
#               MSLP
#               500mb HGHT and VORT
#
# Log :
# D.W.Plummer/NCEP   2/97   Add log header
#
#

if ( ${1} == "-h" || ${1} == "-help" )  then
	echo "Usage: ${0} [printer] [yymmdd/cc]   		      "
        echo "       printer - printer name (default by workstation)	      "
        echo "       yymmdd/cc  - year, month, day and cycle (def most recent)"
	exit
endif

set prt=${1}
set ymdc=${2}

`which prnt`  pmsl        ecmwfg  72 ${prt} ${ymdc}
`which prnt`  500mb_gabsv ecmwfg  72 ${prt} ${ymdc}

`which prnt`  pmsl        ecmwfg  96 ${prt} ${ymdc}
`which prnt`  500mb_gabsv ecmwfg  96 ${prt} ${ymdc}

`which prnt`  pmsl        ecmwfg 120 ${prt} ${ymdc}
`which prnt`  500mb_gabsv ecmwfg 120 ${prt} ${ymdc}

`which prnt`  pmsl        ecmwfg 144 ${prt} ${ymdc}
`which prnt`  500mb_gabsv ecmwfg 144 ${prt} ${ymdc}


exit
