#
#	Makefile for GEMPAK 6.0
#		Follows each limb of source tree
#		Unidata 11/99 Chiz
#
include $(CONFIGDIR)/$(MAKEINC)

all : 
	@( cd melbufr; echo "making $@ in `pwd`" ; \
		$(MAKE) $(MFLAGS) $@ )

install: all

clean:
	@( cd melbufr; echo "making $@ in `pwd`" ; \
		$(MAKE) $(MFLAGS) $@ )
