
name: CI
on: ["push", "pull_request"]

jobs:
  build:
    name: Build ${{ matrix.os_type }} (${{ matrix.os_version }})
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      matrix:
        include:
          - os_type: ubuntu
            os_version: "24.04"
            container_image: ubuntu:24.04
            release_glob: build/dist/*.deb
          - os_type: almalinux
            os_version: "8"
            container_image: quay.io/almalinuxorg/8-base
            release_glob: build/dist/*.rpm
    steps:
    - uses: actions/checkout@v4

    - name: Pull container image
      run: |
        sudo docker pull ${{ matrix.container_image }}

    - name: build
      run: |
        build/setup.sh ${{ matrix.os_type }} ${{ matrix.os_version }}

    - name: Attach assets to GitHub Release
      if: github.ref_type == 'tag'
      uses: softprops/action-gh-release@v2
      with:
        files: |
          ${{ matrix.release_glob }}
        fail_on_unmatched_files: true
